export const data = [
    {id: 1, name: 'Cold cuts',
        price: 5,
        src: require('./imgs/coldcuts.jpg'),
        isSelected: false},
    {id: 2, name: 'Peperoni',
        price: 3.5,
        src: require('./imgs/pepperoni.jpg'),
        isSelected: false},
    {id: 3, name: 'Feta',
        price: 2.5,
        src: require('./imgs/feta.jpg'),
        isSelected: false},
    {id: 4, name: 'Mozzarella',
        price: 1.5,
        src: require('./imgs/mozzarella.jpg'),
        isSelected: false},
    {id: 5, name: 'Swiss cheese',
        price: 3,
        src: require('./imgs/swiss.jpg'),
        isSelected: false},
    {id: 6, name: 'Spices',
        price: 0.5,
        src: require('./imgs/spices.jpg'),
        isSelected: false},
    {id: 7, name: 'Vegetables',
        price: 1.25,
        src: require('./imgs/vegetable.jpg'),
        isSelected: false}
];